### ISSUE TITLE
[FEATURE REQUEST] Rate-limiting mechanisms to API calls

### ISSUE THREAD

**Issue by gruberdev** [WellingtonSilv/API-s-implementations#1]
## Ideia
* Implement a way to limit the number of calls the API makes to prevent the user, even if on purpose, from being temporarily blocked from requesting new data through the library's functions.
### Example
* [Bitfinex REST OHLC API in Python](https://github.com/arthurk/bitfinex-ohlc-import/blob/master/bitfinex/main.py)
#### 'Pythonic' example
```py
for d1, d2 in date_range(start_date, end_date, step):
            # returns (max) 1000 candles, one for every minute
            candles = get_candles(symbol, d1, d2)
            if candles:
                db.insert_candles(symbol, candles)
           # prevent from api rate-limiting
            time.sleep(3)
```
In the example repository, the author limits the number of candles requested to 1000 per minute and implements a timer of 3 seconds between each request. Something similar could be implemented in this library.

**Comment by WellingtonSilv** [comment]
In a unique request the function pull 10000 candles that are the maximum that bitfinex allows per request, the bitfinex_OCHL_data function are making 17 requests per minute and candles public Endpoint have a rate limit of 60/min, i'll add a time sleep of 2 seconds between the requests and that will solve any problem with rate limits :)

**Comment by WellingtonSilv** [comment]
solved with an addiction of a sleep time of 2 seconds between the requests, the user still can pull from 1 to 10000 candles per time with no problems and with no risk to reach rate limits because now even downloading 1 candle per request (what make requests very fast) the function will wait 2 seconds after every request, this give a maximum of 30 requests/min with is only half of rate limits in candles public rest endpoint that is 60 request/min.

The change in the code can be founded in the link bellow:

https://github.com/WellingtonSilv/API-s-implementations/commit/1959ff97fac3462933c917ce02c49c909135c228#diff-4201a115c4327c1bdaac20a66d0eb574
